CREATE TABLE
    IF NOT EXISTS `roles` (
        `id` CHAR(36) NOT NULL,
        `name` VARCHAR(100) NOT NULL,
        `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
        `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (`id`)
    );